# Generated by Django 4.2.7 on 2026-01-10 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aspirationcode_conditioncode_currency_drivetraincode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('make_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehicle_makes',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('body_style', models.CharField(blank=True, help_text='Sedan, SUV, Pickup, Van, Coupe, etc.', max_length=50, null=True)),
                ('year_start', models.SmallIntegerField(blank=True, help_text='First year this model was produced', null=True)),
                ('year_end', models.SmallIntegerField(blank=True, help_text='Last year this model was produced (null if still in production)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.vehiclemake')),
            ],
            options={
                'db_table': 'vehicle_models',
                'ordering': ['make', 'display_order', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='vehiclemodel',
            unique_together={('make', 'name')},
        ),
    ]
