# Generated by Django 4.2.7 on 2026-01-10 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vehicle_catalog_new'),
    ]

    operations = [
        # Drop vehicle_models first (has FK to vehicle_makes)
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS vehicle_models CASCADE;",
            reverse_sql="",  # No reverse, tables were temporary
        ),
        # Drop vehicle_makes
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS vehicle_makes CASCADE;",
            reverse_sql="",
        ),
    ]
