# Generated by Django 4.2.7 on 2026-01-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_vehicle_tables'),
    ]

    operations = [
        # Extend brands table (OEMBrand) using direct SQL
        migrations.RunSQL(
            sql="""
                ALTER TABLE oem.brands 
                ADD COLUMN IF NOT EXISTS brand_type VARCHAR(20) DEFAULT 'PARTS_SUPPLIER' NOT NULL,
                ADD COLUMN IF NOT EXISTS logo_url VARCHAR(200),
                ADD COLUMN IF NOT EXISTS display_order INTEGER DEFAULT 0 NOT NULL,
                ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL;
            """,
            reverse_sql="""
                ALTER TABLE oem.brands
                DROP COLUMN IF EXISTS brand_type,
                DROP COLUMN IF EXISTS logo_url,
                DROP COLUMN IF EXISTS display_order,
                DROP COLUMN IF EXISTS updated_at;
            """,
        ),
        
        # Extend catalog_items table (OEMCatalogItem) using direct SQL
        migrations.RunSQL(
            sql="""
                ALTER TABLE oem.catalog_items
                ADD COLUMN IF NOT EXISTS item_type VARCHAR(20) DEFAULT 'PART' NOT NULL,
                ADD COLUMN IF NOT EXISTS body_style VARCHAR(50),
                ADD COLUMN IF NOT EXISTS year_start SMALLINT,
                ADD COLUMN IF NOT EXISTS year_end SMALLINT,
                ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE NOT NULL,
                ADD COLUMN IF NOT EXISTS display_order INTEGER DEFAULT 0 NOT NULL;
            """,
            reverse_sql="""
                ALTER TABLE oem.catalog_items
                DROP COLUMN IF EXISTS item_type,
                DROP COLUMN IF EXISTS body_style,
                DROP COLUMN IF EXISTS year_start,
                DROP COLUMN IF EXISTS year_end,
                DROP COLUMN IF EXISTS is_active,
                DROP COLUMN IF EXISTS display_order;
            """,
        ),
    ]
