# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_quote_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
