# Generated by Django 4.2.7 on 2026-01-30 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_type_id_column'),
    ]

    operations = [
        # Create the Category table in the cat schema using raw SQL
        migrations.RunSQL(
            """
            -- Create the categories table in the cat schema
            CREATE TABLE IF NOT EXISTS cat.categories (
                category_id SERIAL PRIMARY KEY,
                category_code VARCHAR(20) NOT NULL UNIQUE,
                name VARCHAR(100) NOT NULL,
                description TEXT NULL,
                icon VARCHAR(50) NULL,
                color VARCHAR(20) NULL,
                sort_order INTEGER NOT NULL DEFAULT 0,
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
            );
            
            -- Add comment to table
            COMMENT ON TABLE cat.categories IS 'Equipment categories - replaces static CATEGORY_CHOICES';
            COMMENT ON COLUMN cat.categories.category_id IS 'Primary key';
            COMMENT ON COLUMN cat.categories.category_code IS 'Unique category code';
            COMMENT ON COLUMN cat.categories.name IS 'Category name';
            COMMENT ON COLUMN cat.categories.description IS 'Category description';
            COMMENT ON COLUMN cat.categories.icon IS 'Bootstrap icon class';
            COMMENT ON COLUMN cat.categories.color IS 'Category color for UI';
            COMMENT ON COLUMN cat.categories.sort_order IS 'Display order';
            COMMENT ON COLUMN cat.categories.is_active IS 'Active status';
            COMMENT ON COLUMN cat.categories.created_at IS 'Creation timestamp';
            COMMENT ON COLUMN cat.categories.updated_at IS 'Update timestamp';
            
            -- Create index for ordering
            CREATE INDEX IF NOT EXISTS idx_cat_categories_sort_order 
            ON cat.categories (sort_order, name);
            
            -- Seed initial categories
            INSERT INTO cat.categories (category_code, name, description, icon, color, sort_order, is_active)
            VALUES 
                ('AUTOMOTRIZ', 'Automotriz', 'Vehículos automobiles y ligeross', 'bi-car-front', '#3498db', 1, TRUE),
                ('INDUSTRIAL', 'Industrial', 'Equipos y maquinaria industrial', 'bi-gear-wide-connected', '#9b59b6', 2, TRUE),
                ('AGRICOLA', 'Agrícola', 'Maquinaria agrícola', 'bi-tree', '#27ae60', 3, TRUE),
                ('CONSTRUCCION', 'Construcción', 'Equipos de construcción', 'bi-hammer', '#e67e22', 4, TRUE),
                ('ELECTRONICO', 'Electrónico', 'Equipos electrónicos', 'bi-cpu', '#1abc9c', 5, TRUE),
                ('OTRO', 'Otro', 'Otras categorías', 'bi-box', '#95a5a6', 99, TRUE)
            ON CONFLICT (category_code) DO NOTHING;
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS cat.categories CASCADE;
            """
        ),
        # Update equipment_types to use category_id instead of category (text)
        migrations.RunSQL(
            """
            -- Add the category_id column as nullable first
            ALTER TABLE cat.equipment_types ADD COLUMN IF NOT EXISTS category_id INTEGER NULL;
            
            -- Try to map existing category values to category_id
            UPDATE cat.equipment_types et
            SET category_id = (
                SELECT c.category_id 
                FROM cat.categories c 
                WHERE UPPER(c.category_code) = UPPER(et.category)
            );
            
            -- Set not null after data migration (skip if any NULLs remain)
            ALTER TABLE cat.equipment_types ALTER COLUMN category_id SET NOT NULL;
            
            -- Drop the old category column
            ALTER TABLE cat.equipment_types DROP COLUMN IF EXISTS category;
            
            -- Add foreign key constraint
            ALTER TABLE cat.equipment_types 
            ADD CONSTRAINT fk_equipment_types_category 
            FOREIGN KEY (category_id) REFERENCES cat.categories(category_id) 
            ON DELETE SET NULL;
            
            -- Create index
            CREATE INDEX IF NOT EXISTS idx_equipment_types_category_id 
            ON cat.equipment_types (category_id);
            """,
            reverse_sql="""
            -- Remove foreign key constraint
            ALTER TABLE cat.equipment_types DROP CONSTRAINT IF EXISTS fk_equipment_types_category;
            
            -- Drop index
            DROP INDEX IF EXISTS idx_equipment_types_category_id;
            
            -- Add back the category column
            ALTER TABLE cat.equipment_types ADD COLUMN category VARCHAR(30) NULL;
            
            -- Remove category_id column
            ALTER TABLE cat.equipment_types DROP COLUMN IF EXISTS category_id;
            """
        ),
    ]
