# Generated by Django 4.2.7 on 2026-02-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20260129_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='OEMBrand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('oem_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('brand_type', models.CharField(choices=[('VEHICLE_MFG', 'Vehicle Manufacturer'), ('EQUIPMENT_MFG', 'Equipment Manufacturer'), ('PARTS_SUPPLIER', 'Parts Supplier'), ('MIXED', 'Mixed (Manufacturer & Supplier)')], default='PARTS_SUPPLIER', help_text='Type of brand: vehicle manufacturer, equipment manufacturer, or parts supplier', max_length=20)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo_url', models.URLField(blank=True, help_text='URL to brand logo image', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order for display in lists')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'oem_brands',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
